### ISSUE TITLE
prediction and endpoint

### ISSUE THREAD

**Issue by Pradeep7712000** [brightsparc/sagemaker-safe-deployment-pipeline#10]
can you please tell me what actually its predicting?
and second how it using endpoint.

**Comment by brightsparc** [comment]
Hi, 

Please work through the notebook provisioned as part of the CloudFormation stack to explore this sample.  You will solution deploys an endpoint to is to predict the taxi fare amount in real-time.
https://github.com/brightsparc/sagemaker-safe-deployment-pipeline/blob/master/notebook/mlops.ipynb

**Comment by Pradeep7712000** [comment]
can you please share with me your contact no.
